# Generated by Django 3.1.3 on 2020-11-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_number', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_billing_address', models.CharField(max_length=200)),
                ('customer_shipping_address', models.CharField(max_length=200)),
            ],
        ),
    ]
