# Generated by Django 3.1.3 on 2020-11-13 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_auto_20201113_0610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
